/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'sad' : null } |
  { 'friendship' : null } |
  { 'love' : null } |
  { 'attitude' : null } |
  { 'motivational' : null };
export interface Shayari {
  'id' : bigint,
  'createdAt' : Time,
  'text' : string,
  'author' : string,
  'likes' : bigint,
  'category' : Category,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addShayari' : ActorMethod<[string, string, Category], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLikedShayariIds' : ActorMethod<[Principal], Array<bigint>>,
  'getRandomShayari' : ActorMethod<[Category], [] | [Shayari]>,
  'getShayariByCategory' : ActorMethod<
    [Category, bigint, bigint],
    Array<Shayari>
  >,
  'getTrending' : ActorMethod<[bigint, bigint], Array<Shayari>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeShayari' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchShayari' : ActorMethod<[string], Array<Shayari>>,
  'unlikeShayari' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];