/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'sad' : IDL.Null,
  'friendship' : IDL.Null,
  'love' : IDL.Null,
  'attitude' : IDL.Null,
  'motivational' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Shayari = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
  'author' : IDL.Text,
  'likes' : IDL.Nat,
  'category' : Category,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShayari' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLikedShayariIds' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getRandomShayari' : IDL.Func([Category], [IDL.Opt(Shayari)], []),
  'getShayariByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [IDL.Vec(Shayari)],
      ['query'],
    ),
  'getTrending' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Shayari)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeShayari' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchShayari' : IDL.Func([IDL.Text], [IDL.Vec(Shayari)], ['query']),
  'unlikeShayari' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'sad' : IDL.Null,
    'friendship' : IDL.Null,
    'love' : IDL.Null,
    'attitude' : IDL.Null,
    'motivational' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Shayari = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
    'author' : IDL.Text,
    'likes' : IDL.Nat,
    'category' : Category,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShayari' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLikedShayariIds' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getRandomShayari' : IDL.Func([Category], [IDL.Opt(Shayari)], []),
    'getShayariByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [IDL.Vec(Shayari)],
        ['query'],
      ),
    'getTrending' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Shayari)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeShayari' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchShayari' : IDL.Func([IDL.Text], [IDL.Vec(Shayari)], ['query']),
    'unlikeShayari' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };